---
- hosts: windows
  vars:
    ansible_site_path: "c:\\inetpub\\wwwroot\\MobEAD"
    staging_path: "c:\\deploy"
    ansible_test_staging_path: "{{ staging_path }}\\ansible-mobead-{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}"
  tasks:
  - name: install-iis
    win_feature:
      name: "Web-Server"
      state: present
      restart: no
      include_sub_features: yes
      include_management_tools: no
  - name: create staging path
    win_file: path={{ staging_path }} state=directory

  - name: default-website-index
    win_copy:
      src: ../../application/MobEAD
      dest: "C:\\inetpub\\wwwroot"

  - name: create new website's directory
    win_file: path={{ ansible_site_path }} state=directory
  - name: create new website
    win_iis_website:
      name: "Ansible MobEAD"
      state: started
      port: 8080
      physical_path: "{{ ansible_site_path }}"
  - name: Open site's port on firewall
    win_firewall_rule:
      name: MobEAD
      enable: yes
      state: present
      localport: 8080
      action: Allow
      direction: In
      protocol: Tcp
      force: true
    tags: firewall